apiVersion: apps/v1
kind: Deployment
metadata:
  name: irsa-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irsa-demo
  template:
    metadata:
      labels:
        app: irsa-demo
    spec:
      serviceAccountName: irsa-sa
      containers:
      - name: awscli
        image: amazon/aws-cli
        command: ["sleep","3600"]
